apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nexentastor-csi-driver-pvc-nginx-snapshot-restore
spec:
  storageClassName: nexentastor-csi-driver-cs-nginx-dynamic
  dataSource:
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.ios
    name: nginx-dynamic-volume # vol name
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---